version: '3'
services:
  # Node.js application service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://host.docker.internal:27017/employeeDockerDB'  # Use the service name 'mongo' as the hostname
      PORT: 3000
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db  # Create a volume to persist MongoDB data

volumes:
  mongo-data:
